version: "3.8"
services:
  loki:
    image: grafana/loki:1.5.0
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yaml
    volumes:
      - $PWD/../athena:/mnt/config
    networks:
      - webnet

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
    networks:
      - webnet

  nginx:
    build: $PWD/../nginx
    volumes:
      - $PWD/../vulcan-react/build:/usr/share/nginx/html:ro
      - $PWD/../nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro
      - /$PWD/../vulcan-react/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    networks:
      - webnet
    depends_on:
      - redis
      - mongo
      - nats
      - loki
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
  redis:
    image: redis:alpine
    # command: redis-server --requirepass INSECURE
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/../redis/data:/var/lib/redis
      - $PWD/../redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - webnet
    depends_on: ["loki"]
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=INSECURE
    volumes:
      - $PWD/../mongo/data:/data/db
    networks:
      - webnet
    depends_on: ["loki"]
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
  nats-ui:
    image: sphqxe/nats-webui:latest
    ports:
      - "8087:80"
    networks:
      - webnet
    depends_on: ["nats", "loki"]
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - webnet
    depends_on: ["loki"]
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
  nats-1:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - webnet
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - webnet
    depends_on: ["nats"]
  nats-streaming:
    image: nats-streaming
    networks:
      - webnet

networks:
  webnet:
    name: webnet

volumes:
  portainer_data:
